name: Supabase Edge Function Trigger

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  trigger-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -L -X POST 'https://qfxejgklkwfrkzoaztee.supabase.co/functions/v1/rapid-worker' \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_BEARER_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"name":"Functions"}'
